baseurl = "http://www.romainpoulin.fr"
title = "Romain POULIN"
theme = "hugo-coder"
languagecode = "fr"
defaultcontentlanguage = "fr"

pagination.pagerSize = 20

disqusShortname = ""

[markup.highlight]
style = "github-dark"

[params]
  author = "Romain POULIN"
  info = "Pharmacien"
  description = "Romain POULIN"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  favicon = true
  since = 2023
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/romain-poulin-174832145/"
  target = "_blank"
[[params.social]]
  name = "mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:contact@romainpoulin.fr"
  target = "_blank"

# Menu links
[[menu.main]]
  name = "À propos"
  weight = 1
  url  = "apropos/"
[[menu.main]]
  name = "CV"
  weight = 2
  url  = "cv_fr/"
[[menu.main]]
  name = "Conditions"
  weight = 3
  url  = "conditions/"
[[menu.main]]
  name = "Disponibilités"
  weight = 4
  url = "disponibilites/"

